# Generated by Django 4.2.4 on 2024-04-13 00:31

import account.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, help_text='Биография', null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today, message='Дата рожденияне может быть позже сегодняшнего дня'), django.core.validators.MinValueValidator(limit_value=account.validators.validate_min_year, message='Дата рождения не может быть больше, чем 150 лет назад')], verbose_name='Дата рождения'),
        ),
    ]
