# Generated by Django 5.0.4 on 2024-04-18 01:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Регион', max_length=50, verbose_name='Регион')),
                ('mun_district', models.CharField(help_text='Муниципальный район', max_length=50, verbose_name='Муниципальный район')),
                ('city_type', models.CharField(help_text='Тип поселения', max_length=50, verbose_name='Тип поселения')),
                ('abbreviated_city_type', models.CharField(help_text='Сокращённый тип поселения', max_length=20, verbose_name='Сокращённый тип поселения')),
                ('city', models.CharField(help_text='Населённый пункт', max_length=100, verbose_name='Населённый пункт')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пукты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer', models.BooleanField(help_text='Заказчик', verbose_name='Заказчик')),
                ('description', models.TextField(help_text='Описание', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Оплата', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)], verbose_name='Оплата')),
                ('date', models.DateField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('locality', models.ForeignKey(help_text='Населённый пункт', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.locality', verbose_name='Населённый пункт')),
                ('user', models.ForeignKey(help_text='Заказчик/исполнитель', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик/исполнитель')),
            ],
            options={
                'verbose_name': 'Заказ/предложение',
                'verbose_name_plural': 'Заказы/предложения',
                'ordering': ('-id', '-date'),
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение заказа/предложения', upload_to='order/', verbose_name='Изображение заказа/предложения')),
                ('order', models.ForeignKey(help_text='Заказа/предложение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.order', verbose_name='Заказ/предложение')),
            ],
            options={
                'verbose_name': 'Изображение заказа/предложения',
                'verbose_name_plural': 'Изображении заказов/предложений',
            },
        ),
    ]
