# Generated by Django 4.2.4 on 2024-04-13 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ/предложение', 'verbose_name_plural': 'Заказы/предложения'},
        ),
        migrations.AlterModelOptions(
            name='orderimage',
            options={'verbose_name': 'Изображение заказа/предложения', 'verbose_name_plural': 'Изображении заказов/предложений'},
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(help_text='Город выполения', max_length=50, verbose_name='Город выполения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(help_text='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_сustomer',
            field=models.BooleanField(help_text='Заказчик', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(help_text='Оплата', verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='Заказчик/исполнитель', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик/исполнитель'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='image',
            field=models.ImageField(help_text='Изображение заказа/предложения', upload_to='order/', verbose_name='Изображение заказа/предложения'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='order',
            field=models.ForeignKey(help_text='Заказа/предложение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.order', verbose_name='Заказ/предложение'),
        ),
    ]
