# Generated by Django 4.2.4 on 2024-04-15 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_orderimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_сustomer',
            new_name='is_customer',
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(help_text='Оплата', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)], verbose_name='Оплата'),
        ),
    ]
